# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureDay',
            fields=[
                ('day', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='LecturePoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attended', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lecture_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.LectureDay')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
