# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20170422_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureday',
            name='code',
            field=models.UUIDField(default=education.models.lecture_code_handler, primary_key=True, serialize=False),
        ),
    ]
