# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20170422_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureday',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='lectureday',
            name='start_date',
        ),
        migrations.AddField(
            model_name='lectureday',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
